apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: dea
  labels:
    app: nginx

spec:
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
      - name: nginxcontainer
        image: nginx:trixie-perl
        ports:
        - containerPort: 80

      nodeSelector:
        size: mid

      resources:
        requests:
          cpu: 1
          memory: "1Gi"

        limits:
          cpu: 2
          memory: "2Gi"
