apiVersion: v1

kind: Pod

metadata:
  name: nginxpod
  # namespace: nginx
  labels:
    app: nginx

spec:
  containers:
  - name: nginxcontainer
    image: nginx:trixie-perl
    ports:
    - containerPort: 80

    env:
    - name: name
      valueFrom:
        configMapKeyRef:
          name: cm
          key: name
  # priorityClassName: high-priority
