apiVersion: apps/v1
kind: Deployment

metadata:
  name: de
  labels:
    app: nginx

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
      - name: nginx
        image: nginx:trixie-perl
        ports:
        - containerPort: 80

        env:
        - name: name
          valueFrom:
            configMapKeyRef:
              name: cm
              key: name

      resources:
        requests:
          cpu: 1
          memory: "1Gi"

        limits:
          cpu: 1
          memory: "2Gi"

      tolerations:
      - key: "app"
        value: "nginx"
        effect: "NoSchedule"
