apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginxdeployment
  labels:
    app: nginx

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
      - name: nginc
        image: nginx:trixie-perl
        ports:
        - containerPort: 80

        env:
        - name: name
          value: "yash"

      resources:
        requests:
          cpu: "2"
          memory: "1Gi"

        limits:
          cpu: "2"
          memory: "1Gi"
